### ISSUE TITLE
Keep latest tag up to date

### ISSUE THREAD

**Issue by nemchik** [PeterDaveHello/docker-yamllint#2]
I notice that as of writing https://hub.docker.com/r/peterdavehello/yamllint/tags latest tag is showing
```
$ docker run --rm peterdavehello/yamllint
yamllint 1.24.1
```
but the actual newest version available by tag is 1.25.0

Is there any way you could adjust your build logic to update the latest tag?

**Comment by PeterDaveHello** [comment]
@nemchik Thanks for reporting this, should be fixed now! Please try again!
